### ISSUE TITLE
React error due to eslint

### ISSUE THREAD

**Issue by esmaeilmirzaee** [milespratt/bingmaps-react#23]
First and foremost thanks for the project. I found the following problem in a fresh created project. Could you help me with the issue?

![image](https://user-images.githubusercontent.com/8766916/99884631-ce223280-2bfd-11eb-8adb-f3fd1774ca28.png)

![image](https://user-images.githubusercontent.com/8766916/99884289-1ab83e80-2bfb-11eb-84ad-1839553dd71d.png)

**Comment by hsluoyz** [comment]
@milespratt @esmaeilmirzaee hi, I encountered exactly the same issue, how did you fix it? Thanks.

![image](https://user-images.githubusercontent.com/3787410/101283813-d8f0e000-3817-11eb-830d-23ce8a8c3568.png)

![image](https://user-images.githubusercontent.com/3787410/101283823-e5753880-3817-11eb-8ba6-3ca089dacb7b.png)

**Comment by hsluoyz** [comment]
@milespratt can we remove the `babel-eslint` dependency as it seems to cause the above error?

**Comment by esmaeilmirzaee** [comment]
Hi,

I couldn't solve the problem yet, unfortunately.

**Comment by hsluoyz** [comment]
Updating the dependencies to the same of your own project solves the issue, see my fork: https://github.com/hsluoyz/bingmaps-react/commit/c37a1965146bc32e0b448efe1878bfd75607cbc0

**Comment by esmaeilmirzaee** [comment]
Thanks, I'll check it out.

Yours sincerely,
Esmaeil MIRZAEE,
esmaeilmirzaee.github.io
