### ISSUE TITLE
Cannot find module 'bingmaps-react' while testing with jest

### ISSUE THREAD

**Issue by Spomsoree** [milespratt/bingmaps-react#32]
The module works fine while running the app, but we get the following error in the jest test environment:

`Cannot find module 'bingmaps-react' from 'src/components/stateless/atomic/Map/index.js'`

Is there a workaround to this problem, or a simple fix I'm missing?

**Comment by Ellezique** [comment]
I tried with testing-library/react and jest - same error.

**Comment by Spomsoree** [comment]
Worked for me, thank you very much!
