### ISSUE TITLE
Use multiple Instances of BingMapsReact Component

### ISSUE THREAD

**Issue by ruthoferroman** [milespratt/bingmaps-react#58]
I want to use multiple instances of BingMapsReact component on one screen.  When I try to do so i get the following errors on each instance:

`mapcontrol?callback=makeMap:12  
       Uncaught TypeError: Cannot read properties of undefined (reading 'heading')
    at n.constructView (VM3541 2nIzc7VnJnL4bbR8O2puCQKoiKs.js:1:201695)
    at u._setViewInternal (VM3548 dcHS7nT2K1gkKSdMvs59EvdUTfc.js:1:83546)
    at u.setView (VM3548 dcHS7nT2K1gkKSdMvs59EvdUTfc.js:1:82562)
    at setMapViewOptions (index.js:102:1)
    at index.js:140:1
    at Microsoft.Maps.notifyMapReadyForBootstrap (mapcontrol?callback=makeMap:12:7274)
    at VM3548 dcHS7nT2K1gkKSdMvs59EvdUTfc.js:1:120205
    at VM3548 dcHS7nT2K1gkKSdMvs59EvdUTfc.js:1:120304`

and

`Uncaught TypeError: Microsoft.Maps.NetworkCallbacks.f_logCallbackRequest is not a function
    at Log?entry=0&fmt=1&type=3&group=MapControl&name=MVC&version=v8&mkt=de-AT&auth=Au3j6PhQC5-8vZV4H33Ltc7S1ww2dhsp8wVs4B-D42R_ScS2kwCEJ_UXATcPUwfA&jsonp=Microsoft.Maps.NetworkCallbacks.f_logCallbackRequest:1:33
(anonym) @ Log?entry=0&fmt=1&type=3&group=MapControl&name=MVC&version=v8&mkt=de-AT&auth=Au3j6PhQC5-8vZV4H33Ltc7S1ww2dhsp8wVs4B-D42R_ScS2kwCEJ_UXATcPUwfA&jsonp=Microsoft.Maps.NetworkCallbacks.f_logCallbackRequest:1`

Any ideas what goes wrong here?

**Comment by ruthoferroman** [comment]
might be related to #56

**Comment by milespratt** [comment]
I was not able to get multiple instances working. Feel free to open a PR if you get it working.
