### ISSUE TITLE
the specified credentials are invalid 

### ISSUE THREAD

**Issue by ranesh84** [milespratt/bingmaps-react#67]
Hi,

I was using react-bingmaps and same key working but when I replacing that and adding [bingmaps-react](https://github.com/milespratt/bingmaps-react) it's start throwing me error the specified credentials are invalid. Kindly suggest.

**Comment by generalleger** [comment]
I'm experiencing the same issue

**Comment by generalleger** [comment]
figured it out...

be sure to change `bingmapKey` to `bingMapsKey`

**Comment by ranesh84** [comment]
I am able to figure out the issue. thank you @generalleger for your suggestion.
